// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug.proto

/*
Package debug is a generated protocol buffer package.

It is generated from these files:
	debug.proto

It has these top-level messages:
	MDebugTos
	MRestartTos
	MBuildTableTos
	MBuildTableToc
	MBuildProjectTos
	MBuildProjectToc
	MBuildMapTos
	MBuildMapToc
	MBuildSceneTos
	MBuildSceneToc
*/
package debug

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// debug
type MDebugTos struct {
	Type             *int32  `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	ParamList        []int32 `protobuf:"varint,2,rep,name=param_list,json=paramList" json:"param_list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MDebugTos) Reset()                    { *m = MDebugTos{} }
func (m *MDebugTos) String() string            { return proto.CompactTextString(m) }
func (*MDebugTos) ProtoMessage()               {}
func (*MDebugTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MDebugTos) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MDebugTos) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

// 重启
type MRestartTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MRestartTos) Reset()                    { *m = MRestartTos{} }
func (m *MRestartTos) String() string            { return proto.CompactTextString(m) }
func (*MRestartTos) ProtoMessage()               {}
func (*MRestartTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 生成数据
type MBuildTableTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildTableTos) Reset()                    { *m = MBuildTableTos{} }
func (m *MBuildTableTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildTableTos) ProtoMessage()               {}
func (*MBuildTableTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 生成数据
type MBuildTableToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildTableToc) Reset()                    { *m = MBuildTableToc{} }
func (m *MBuildTableToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildTableToc) ProtoMessage()               {}
func (*MBuildTableToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MBuildTableToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 编译项目
type MBuildProjectTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildProjectTos) Reset()                    { *m = MBuildProjectTos{} }
func (m *MBuildProjectTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildProjectTos) ProtoMessage()               {}
func (*MBuildProjectTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 编译项目
type MBuildProjectToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildProjectToc) Reset()                    { *m = MBuildProjectToc{} }
func (m *MBuildProjectToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildProjectToc) ProtoMessage()               {}
func (*MBuildProjectToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MBuildProjectToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 生成地图数据
type MBuildMapTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildMapTos) Reset()                    { *m = MBuildMapTos{} }
func (m *MBuildMapTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildMapTos) ProtoMessage()               {}
func (*MBuildMapTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

// 生成地图数据
type MBuildMapToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildMapToc) Reset()                    { *m = MBuildMapToc{} }
func (m *MBuildMapToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildMapToc) ProtoMessage()               {}
func (*MBuildMapToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MBuildMapToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 生成场景数据
type MBuildSceneTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildSceneTos) Reset()                    { *m = MBuildSceneTos{} }
func (m *MBuildSceneTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildSceneTos) ProtoMessage()               {}
func (*MBuildSceneTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// 生成场景数据
type MBuildSceneToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildSceneToc) Reset()                    { *m = MBuildSceneToc{} }
func (m *MBuildSceneToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildSceneToc) ProtoMessage()               {}
func (*MBuildSceneToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MBuildSceneToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*MDebugTos)(nil), "m_debug_tos")
	proto.RegisterType((*MRestartTos)(nil), "m_restart_tos")
	proto.RegisterType((*MBuildTableTos)(nil), "m_build_table_tos")
	proto.RegisterType((*MBuildTableToc)(nil), "m_build_table_toc")
	proto.RegisterType((*MBuildProjectTos)(nil), "m_build_project_tos")
	proto.RegisterType((*MBuildProjectToc)(nil), "m_build_project_toc")
	proto.RegisterType((*MBuildMapTos)(nil), "m_build_map_tos")
	proto.RegisterType((*MBuildMapToc)(nil), "m_build_map_toc")
	proto.RegisterType((*MBuildSceneTos)(nil), "m_build_scene_tos")
	proto.RegisterType((*MBuildSceneToc)(nil), "m_build_scene_toc")
}

func init() { proto.RegisterFile("debug.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x86, 0xd9, 0xee, 0x76, 0xa1, 0x53, 0x96, 0xd2, 0x94, 0x95, 0x5e, 0x84, 0x92, 0x53, 0x45,
	0xf4, 0x19, 0x7c, 0x00, 0x4f, 0x7d, 0x81, 0x90, 0xb6, 0x83, 0x54, 0x12, 0x13, 0x92, 0xe9, 0xc1,
	0xb7, 0x17, 0xa3, 0x05, 0xb1, 0xf6, 0x36, 0xf3, 0xf1, 0xcf, 0x37, 0xfc, 0x90, 0xf6, 0xd8, 0x8e,
	0xa7, 0xbd, 0x75, 0x86, 0x0c, 0x3f, 0x40, 0xaa, 0x45, 0x00, 0x82, 0x8c, 0x67, 0x0c, 0x7e, 0xe8,
	0x6a, 0xb1, 0xfc, 0xaa, 0xa2, 0x3a, 0x6e, 0xc2, 0xcc, 0xd6, 0x00, 0x56, 0x3a, 0xa9, 0x85, 0x1a,
	0x3c, 0x95, 0x51, 0xf5, 0x5d, 0xc7, 0x4d, 0x12, 0xc8, 0x71, 0xf0, 0xc4, 0x33, 0xf8, 0xd3, 0xc2,
	0xa1, 0x27, 0xe9, 0xe8, 0xee, 0xe0, 0x05, 0xe4, 0x5a, 0xb4, 0xe3, 0xa0, 0x7a, 0x41, 0xb2, 0x55,
	0x18, 0xe0, 0x76, 0x0e, 0x3b, 0xb6, 0x82, 0x5f, 0x87, 0x7e, 0x54, 0x14, 0xfe, 0x25, 0xcd, 0x73,
	0xe3, 0xff, 0x50, 0x4c, 0x61, 0xeb, 0xcc, 0x19, 0xbb, 0x87, 0x78, 0xf7, 0x09, 0x2f, 0x5b, 0x72,
	0xc8, 0xa6, 0xb8, 0x96, 0x36, 0x18, 0x36, 0xef, 0x68, 0xf9, 0xfa, 0xa5, 0x85, 0xef, 0xf0, 0x32,
	0x6b, 0x31, 0xc1, 0x45, 0xc3, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x91, 0xf4, 0x82, 0x17, 0x68, 0x01,
	0x00, 0x00,
}
